import {SUPABASE_URL,SUPABASE_KEY} from './config.js';
import {healthScore,bmi,bmiClass,waistHeight} from './health.js';
import {drawChart} from './charts.js';
import {coachText} from './coach.js';

const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY),$=x=>document.getElementById(x);
let session=null,p=null,rows=[],chart='weight';
const val=x=>$(x).value===''?null:Number($(x).value),msg=(id,t,e=0)=>$(id).innerHTML=t?'<div class="status '+(e?'error':'')+'">'+t+'</div>':'';

function nearestBefore(days){if(!rows.length)return null;const target=new Date(rows.at(-1).entry_date);target.setDate(target.getDate()-days);let best=null;for(const r of rows){if(new Date(r.entry_date)<=target)best=r}return best}
async function boot(){if(localStorage.theme==='dark')document.body.classList.add('dark');$('date').value=new Date().toISOString().slice(0,10);$('time').textContent=new Date().toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'});let {data}=await sb.auth.getSession();session=data.session;await ui();sb.auth.onAuthStateChange(async(_,s)=>{session=s;await ui()})}
async function ui(){$('auth').classList.toggle('hidden',!!session);$('app').classList.toggle('hidden',!session);$('nav').classList.toggle('hidden',!session);if(session)await load()}
async function load(){let a=await sb.from('profiles').select('*').eq('id',session.user.id).single();p=a.data;let b=await sb.from('progress_entries').select('*').eq('user_id',session.user.id).order('entry_date');rows=b.data||[];$('name').value=p?.full_name||'';$('height').value=p?.height_cm||'';$('mid').value=p?.intermediate_goal_kg||'';$('final').value=p?.final_goal_kg||'';$('hello').textContent='Hola, '+(p?.full_name||'');let f=await sb.from('families').select('*');$('familyCode').textContent=(f.data||[]).find(x=>x.owner_id===session.user.id)?.invite_code||'MIEMBRO';render()}
function render(){if(!rows.length){$('list').innerHTML='Sin registros';drawChart($('chart'),rows,chart);return}
 const first=rows[0],last=rows.at(-1),prev=rows.at(-2),goal=Number(p?.intermediate_goal_kg||p?.final_goal_kg||0),score=healthScore(last);
 $('weightNow').textContent=Number(last.weight_kg).toFixed(2)+' kg';$('score').textContent=score;$('scoreRing').style.background='conic-gradient(var(--pri) '+score*3.6+'deg,#e8eeee 0deg)';
 const wd=prev?Number(last.weight_kg)-Number(prev.weight_kg):0;$('weeklyDelta').textContent=prev?(wd<=0?'↓ ':'↑ ')+Math.abs(wd).toFixed(2)+' kg vs anterior':'Primer registro';
 const b=bmi(Number(last.weight_kg),Number(p?.height_cm||0));$('bmi').textContent=b?b.toFixed(1):'—';$('bmiClass').textContent=b?bmiClass(b):'Configura estatura';
 const waist=[...rows].reverse().find(r=>r.waist_cm!=null),ratio=waistHeight(Number(waist?.waist_cm||0),Number(p?.height_cm||0));$('whr').textContent=ratio?ratio.toFixed(2):'—';$('whrText').textContent=waist?'Cintura '+waist.waist_cm+' cm':'Registra cintura';
 renderPeriod(7,'change7','change7Text');renderPeriod(30,'change30','change30Text');
 $('goalTitle').textContent=goal?'Camino a '+goal+' kg':'Camino a tu meta';const pc=goal?Math.max(0,Math.min(100,(first.weight_kg-last.weight_kg)/(first.weight_kg-goal)*100)):0;$('progressBar').style.width=pc+'%';$('goalText').textContent=goal?'Avance '+pc.toFixed(0)+'% · faltan '+Math.max(0,last.weight_kg-goal).toFixed(2)+' kg':'Configura meta';
 const recent=rows.slice(-4);if(goal&&recent.length>=2){const days=(new Date(recent.at(-1).entry_date)-new Date(recent[0].entry_date))/86400000,rate=(recent[0].weight_kg-recent.at(-1).weight_kg)/(days||1);$('projection').textContent=rate>0?Math.ceil((last.weight_kg-goal)/rate)+' días aprox.':'Sin proyección'}
 renderMilestones(last.weight_kg);renderCalculated(first,last);renderEngineering(last,prev);$('coach').textContent=coachText(last);renderList();drawChart($('chart'),rows,chart);
}
function renderPeriod(days,id,textId){const old=nearestBefore(days),last=rows.at(-1);if(!old){$(id).textContent='—';$(textId).textContent='Sin datos suficientes';return}const d=Number(last.weight_kg)-Number(old.weight_kg);$(id).textContent=(d>0?'+':'')+d.toFixed(2)+' kg';$(textId).textContent=d<0?'Bajaste en el periodo':d>0?'Subiste en el periodo':'Sin cambio'}
function renderMilestones(weight){$('milestones').innerHTML=[125,120,115,110,105,100,95].map(x=>'<span class="milestone '+(weight<=x?'done':'')+'">'+x+' kg</span>').join('')}
function renderCalculated(first,last){const lost=Number(first.weight_kg)-Number(last.weight_kg),pct=lost/Number(first.weight_kg)*100,best=Math.min(...rows.map(r=>Number(r.weight_kg))),avg=rows.slice(-7).reduce((a,r)=>a+Number(r.weight_kg),0)/Math.min(7,rows.length);const item=(a,b)=>'<div class="calc-item"><span>'+a+'</span><strong>'+b+'</strong></div>';$('calculated').innerHTML=item('Pérdida total',(lost>=0?'-':'+')+Math.abs(lost).toFixed(2)+' kg')+item('% peso inicial',(pct>=0?'-':'+')+Math.abs(pct).toFixed(1)+'%')+item('Mejor peso',best.toFixed(2)+' kg')+item('Promedio reciente',avg.toFixed(2)+' kg')+item('Distancia a mejor',(Number(last.weight_kg)-best).toFixed(2)+' kg')+item('Registros',rows.length)}
function ind(name,state,trend){return '<div class="indicator"><b>'+name+'</b><span class="state '+state+'">'+(state==='good'?'● Bien':state==='warn'?'● Atención':'● Crítico')+'</span><span>'+trend+'</span></div>'}
function renderEngineering(e,prev){const w=prev?(e.weight_kg<prev.weight_kg?'↓':e.weight_kg>prev.weight_kg?'↑':'→'):'—';$('engineering').innerHTML=ind('Peso',w==='↓'?'good':w==='↑'?'warn':'good',w)+ind('Agua',e.water_liters>=2.5?'good':'warn',(e.water_liters||0)+' L')+ind('Sueño',e.sleep_hours>=7?'good':'bad',(e.sleep_hours||0)+' h')+ind('Ansiedad',e.anxiety_score<=5?'good':e.anxiety_score<=7?'warn':'bad',(e.anxiety_score??'—')+'/10')+ind('Actividad',(e.exercise_minutes||0)>=20?'good':'warn',(e.exercise_minutes||0)+' min')}
function renderList(){$('list').innerHTML=[...rows].reverse().map(r=>'<div class="entry"><b>'+Number(r.weight_kg).toFixed(2)+' kg</b><small>'+r.entry_date+' · '+new Date(r.created_at).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'})+'</small><small>'+((r.notes||'').replace('[DIETA_OK]',''))+'</small><button class="danger" onclick="window.del(\''+r.id+'\')">Eliminar</button></div>').join('')}
window.del=async id=>{if(confirm('¿Eliminar?')){await sb.from('progress_entries').delete().eq('id',id);await load()}};
$('login').onclick=async()=>{let {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('pass').value});msg('authMsg',error?.message||'',!!error)};$('signup').onclick=async()=>{let {error}=await sb.auth.signUp({email:$('email').value,password:$('pass').value,options:{data:{full_name:$('email').value.split('@')[0]}}});msg('authMsg',error?error.message:'Cuenta creada. Revisa tu correo.',!!error)};$('logout').onclick=()=>sb.auth.signOut();
$('form').onsubmit=async e=>{e.preventDefault();let notes=($('diet').value==='true'?'[DIETA_OK] ':'')+$('notes').value;let row={user_id:session.user.id,entry_date:$('date').value,weight_kg:val('w'),water_liters:val('water'),sleep_hours:val('sleep'),hunger_score:val('hunger'),anxiety_score:val('anxiety'),walking_days:val('walks'),exercise_minutes:val('exercise'),had_chips:$('chips').value===''?null:$('chips').value==='true',waist_cm:val('waist'),chest_cm:val('chest'),hip_cm:val('hip'),arm_cm:val('arm'),thigh_cm:val('thigh'),notes:notes||null};let {error}=await sb.from('progress_entries').upsert(row,{onConflict:'user_id,entry_date'});msg('saveMsg',error?error.message:'Guardado',!!error);if(!error){e.target.reset();$('date').value=new Date().toISOString().slice(0,10);await load()}};
$('saveProfile').onclick=async()=>{let {error}=await sb.from('profiles').update({full_name:$('name').value,height_cm:val('height'),intermediate_goal_kg:val('mid'),final_goal_kg:val('final')}).eq('id',session.user.id);msg('profileMsg',error?error.message:'Perfil actualizado',!!error);if(!error)await load()};$('join').onclick=async()=>{let {error}=await sb.rpc('join_family_by_code',{supplied_code:$('joinCode').value});msg('familyMsg',error?error.message:'Unido',!!error)};
$('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.theme=document.body.classList.contains('dark')?'dark':'light'};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(q=>q.classList.remove('on'));b.classList.add('on');chart=b.dataset.chart;drawChart($('chart'),rows,chart)});document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(q=>q.classList.remove('on'));b.classList.add('on');document.querySelectorAll('.screen').forEach(q=>q.classList.remove('on'));$(b.dataset.screen).classList.add('on');setTimeout(()=>drawChart($('chart'),rows,chart),30)});window.onresize=()=>drawChart($('chart'),rows,chart);boot();